# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirflowCli < Formula
  desc "Interact with airflow REST API from your CLI"
  homepage "https://github.com/pjgaetan/airflow-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Darwin_arm64.tar.gz"
      sha256 "06107338486040cf98c722909220fab4d7898a79f9d6377228175e0f77392f67"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "eeea3b58775a351555da3348a0e95baf5b419dbf5b858d04b7015171aaea88ed"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Linux_arm64.tar.gz"
      sha256 "4f5de42c1252e5f2c08f99835618076da777a6a664d71d041a656801188cc1f5"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Linux_x86_64.tar.gz"
      sha256 "5b3eb93e0d0ab7434cca29b331f73b052e5a8a2b52321ed46c2c2f779c8dd740"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Linux_armv6.tar.gz"
      sha256 "8909038ec97b419d0f18c1fe5d5c65b428f8cfbc04ab125901a90319caa02cc9"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
  end

  head do
    url "https://github.com/pjgaetan/airflow-cli.git", branch: "main"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/airflow-cli help")
    assert_includes help_text, "Airflow CLI"
  end
end
