# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirflowCli < Formula
  desc "Interact with airflow REST API from your CLI"
  homepage "https://github.com/pjgaetan/airflow-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Darwin_arm64.tar.gz"
      sha256 "e662fda5fcc384a3f7ecd494074a7329b9402b6119c65b6a3293d6b1c0aecd8d"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "d2134f20cfabb22ce14fcb85d507684f815b8aa0c095d2c617491498de44ad37"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Linux_arm64.tar.gz"
      sha256 "0971f7028bfb757c4d8b973b6dd5e6e2d06d8a5d1d58ddd2335793ea4c63b5c4"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Linux_x86_64.tar.gz"
      sha256 "3ba37c2b8aba66597b04b705bb4d6ac96d7f1bae8a95017448035355bccb4552"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.0.3/airflow-cli_0.0.3_Linux_armv6.tar.gz"
      sha256 "d26471c708545d924955518a4754366ef4da575946f8f5538eb4625396f4e867"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
  end

  head do
    url "https://github.com/pjgaetan/airflow-cli.git", branch: "main"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/airflow-cli help")
    assert_includes help_text, "Airflow CLI"
  end
end
