# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AriflowCli < Formula
  desc "Interact with airflow REST API from your CLI"
  homepage "https://github.com/pjgaetan/airflow-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.1.0/airflow-cli_ 0.1.0_Darwin_x86_64.tar.gz"
      sha256 "699e381a5c5dba29c0a057e90ebea4f6fbeb1f18fb49f18c3403a75f4bc9e106"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.1.0/airflow-cli_ 0.1.0_Darwin_arm64.tar.gz"
      sha256 "c3b36fd6ca2a5e3c24d95ac8baf0a4d45c3024e95efe0d0c4fd0e9cb6c51800b"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.1.0/airflow-cli_ 0.1.0_Linux_armv6.tar.gz"
      sha256 "30e45fed8f7e76c00530f1c67c4f6d6b82a1c1986cd7286b1a9882dfeaca0bff"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.1.0/airflow-cli_ 0.1.0_Linux_arm64.tar.gz"
      sha256 "0692ad50171f294ca902b457d4a7f0622c6953f3525b10eeabb1646f1ffd88a4"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PJGaetan/airflow-cli/releases/download/v0.1.0/airflow-cli_ 0.1.0_Linux_x86_64.tar.gz"
      sha256 "658a48cbfb34d1453125dd5b1a273bb6a8e6b4452fb02bcc3bbc497cc438e94c"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/airflow-cli"
        else
          bin.install File.exist?("bin/airflow-cli") ? "bin/airflow-cli" : "airflow-cli"
        end
      end
    end
  end

  head do
    url "https://github.com/pjgaetan/airflow-cli.git", branch: "main"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/airflow-cli help")
    assert_includes help_text, "Airflow CLI"
  end
end
